### ISSUE TITLE
Examples for table sorting and pagination

### ISSUE THREAD

**Issue by dioxic** [karakum-team/kotlin-react-table-sample#12]
It's not all that obvious (to me) how to do sorting or pagination in the tanstack table v8. Can we get an example of these features?

**Comment by aerialist7** [comment]
Hi @dioxic,

here you can find [Sorting example](https://tanstack.com/table/v8/docs/examples/react/sorting) and [Pagination example](https://tanstack.com/table/v8/docs/examples/react/pagination).

It's so easy to adapt these samples to Kotlin.
Please try and you're welcome if any questions appears ;)

P.S. PRs for Sorting and Paging are also welcome :)
